"""create bls_nutrition table

Revision ID: 4af6025009eb
Revises: 
Create Date: 2025-08-11 14:19:49.210041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4af6025009eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_nutrition',
    sa.Column('bls_number', sa.String(), nullable=False),
    sa.Column('name_german', sa.String(), nullable=True),
    sa.Column('nutrients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('bls_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bls_nutrition')
    # ### end Alembic commands ###
