""" initial_correct_bls_schema

Revision ID: 5480992e75c3
Revises: 
Create Date: 2025-08-15 15:12:51.728588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5480992e75c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_nutrition',
    sa.Column('SBLS', sa.String(length=7), nullable=False),
    sa.Column('ST', sa.String(), nullable=False),
    sa.Column('STE', sa.String(), nullable=True),
    sa.Column('GCAL', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('GJ', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('GCALZB', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('GJZB', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ZW', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ZE', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ZF', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ZK', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ZB', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ZM', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ZO', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ZA', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VA', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VAR', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VAC', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VD', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VE', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VEAT', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VK', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB3A', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB5', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB6', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB7', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB9G', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VB12', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('VC', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MNA', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MK', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MCA', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MMG', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MP', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MCL', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MFE', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MZN', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MCU', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MMN', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MF', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('MJ', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KAM', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KAS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KAX', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KA', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KMT', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KMF', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KMG', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KM', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KDS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KDM', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KDL', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KD', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KMD', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KPOR', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KPON', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KPG', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KPS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KP', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KBP', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KBH', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KBU', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KBC', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KBL', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KBW', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('KBN', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EILE', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ELEU', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ELYS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EMET', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ECYS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EPHE', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ETYR', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ETHR', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ETRP', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EVAL', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EARG', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EHIS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EEA', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EALA', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EASP', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EGLU', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EGLY', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EPRO', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ESER', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ENA', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EH', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('EP', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F40', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F60', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F80', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F100', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F120', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F140', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F150', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F160', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F170', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F180', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F200', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F220', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F240', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F141', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F151', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F161', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F171', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F181', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F201', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F221', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F241', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FU', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F162', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F164', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F182', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F183', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F184', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F193', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F202', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F203', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F204', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F205', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F222', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F223', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F224', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F225', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('F226', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FP', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FK', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FM', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FL', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FO3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FO6', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FG', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('FC', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('GFPS', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('GKB', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('GMKO', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('GP', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.CheckConstraint('"SBLS" ~ \'^[B-Y][0-9]{6}$\'', name='ck_bls_number_format'),
    sa.PrimaryKeyConstraint('SBLS')
    )
    op.create_index(op.f('ix_bls_nutrition_SBLS'), 'bls_nutrition', ['SBLS'], unique=False)
    op.create_index(op.f('ix_bls_nutrition_ST'), 'bls_nutrition', ['ST'], unique=False)
    op.create_index(op.f('ix_bls_nutrition_STE'), 'bls_nutrition', ['STE'], unique=False)
    op.create_index('ix_blsnutrition_STE_trgm', 'bls_nutrition', ['STE'], unique=False, postgresql_using='gin', postgresql_ops={'STE': 'gin_trgm_ops'})
    op.create_index('ix_blsnutrition_ST_trgm', 'bls_nutrition', ['ST'], unique=False, postgresql_using='gin', postgresql_ops={'ST': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blsnutrition_ST_trgm', table_name='bls_nutrition', postgresql_using='gin', postgresql_ops={'ST': 'gin_trgm_ops'})
    op.drop_index('ix_blsnutrition_STE_trgm', table_name='bls_nutrition', postgresql_using='gin', postgresql_ops={'STE': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_bls_nutrition_STE'), table_name='bls_nutrition')
    op.drop_index(op.f('ix_bls_nutrition_ST'), table_name='bls_nutrition')
    op.drop_index(op.f('ix_bls_nutrition_SBLS'), table_name='bls_nutrition')
    op.drop_table('bls_nutrition')
    # ### end Alembic commands ###
